++++++[>++++++++++++<-]>.   print 'H'
<++++[>+++++++<-]>+.        print 'e'
+++++++..                   print 'l' twice
+++.                        print 'o'
>>>++++[>++++++++<-]>.      print ' '
<<<<++++++++.               print 'w'
--------.                   print 'o'
+++.                        print 'r'
------.                     print 'l'
--------.                   print 'd'